/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package hu.bme.mit.gitlens;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-04-04")
public class ServerResponse implements org.apache.thrift.TBase<ServerResponse, ServerResponse._Fields>, java.io.Serializable, Cloneable, Comparable<ServerResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ServerResponse");

  private static final org.apache.thrift.protocol.TField RESPONSE_FIELD_DESC = new org.apache.thrift.protocol.TField("Response", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField RETURN_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("ReturnValue", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ServerResponseStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ServerResponseTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String Response; // required
  public long ReturnValue; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RESPONSE((short)1, "Response"),
    RETURN_VALUE((short)2, "ReturnValue");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESPONSE
          return RESPONSE;
        case 2: // RETURN_VALUE
          return RETURN_VALUE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RETURNVALUE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESPONSE, new org.apache.thrift.meta_data.FieldMetaData("Response", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.RETURN_VALUE, new org.apache.thrift.meta_data.FieldMetaData("ReturnValue", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ServerResponse.class, metaDataMap);
  }

  public ServerResponse() {
  }

  public ServerResponse(
    java.lang.String Response,
    long ReturnValue)
  {
    this();
    this.Response = Response;
    this.ReturnValue = ReturnValue;
    setReturnValueIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ServerResponse(ServerResponse other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetResponse()) {
      this.Response = other.Response;
    }
    this.ReturnValue = other.ReturnValue;
  }

  public ServerResponse deepCopy() {
    return new ServerResponse(this);
  }

  @Override
  public void clear() {
    this.Response = null;
    setReturnValueIsSet(false);
    this.ReturnValue = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getResponse() {
    return this.Response;
  }

  public ServerResponse setResponse(@org.apache.thrift.annotation.Nullable java.lang.String Response) {
    this.Response = Response;
    return this;
  }

  public void unsetResponse() {
    this.Response = null;
  }

  /** Returns true if field Response is set (has been assigned a value) and false otherwise */
  public boolean isSetResponse() {
    return this.Response != null;
  }

  public void setResponseIsSet(boolean value) {
    if (!value) {
      this.Response = null;
    }
  }

  public long getReturnValue() {
    return this.ReturnValue;
  }

  public ServerResponse setReturnValue(long ReturnValue) {
    this.ReturnValue = ReturnValue;
    setReturnValueIsSet(true);
    return this;
  }

  public void unsetReturnValue() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RETURNVALUE_ISSET_ID);
  }

  /** Returns true if field ReturnValue is set (has been assigned a value) and false otherwise */
  public boolean isSetReturnValue() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RETURNVALUE_ISSET_ID);
  }

  public void setReturnValueIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RETURNVALUE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case RESPONSE:
      if (value == null) {
        unsetResponse();
      } else {
        setResponse((java.lang.String)value);
      }
      break;

    case RETURN_VALUE:
      if (value == null) {
        unsetReturnValue();
      } else {
        setReturnValue((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case RESPONSE:
      return getResponse();

    case RETURN_VALUE:
      return getReturnValue();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case RESPONSE:
      return isSetResponse();
    case RETURN_VALUE:
      return isSetReturnValue();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof ServerResponse)
      return this.equals((ServerResponse)that);
    return false;
  }

  public boolean equals(ServerResponse that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_Response = true && this.isSetResponse();
    boolean that_present_Response = true && that.isSetResponse();
    if (this_present_Response || that_present_Response) {
      if (!(this_present_Response && that_present_Response))
        return false;
      if (!this.Response.equals(that.Response))
        return false;
    }

    boolean this_present_ReturnValue = true;
    boolean that_present_ReturnValue = true;
    if (this_present_ReturnValue || that_present_ReturnValue) {
      if (!(this_present_ReturnValue && that_present_ReturnValue))
        return false;
      if (this.ReturnValue != that.ReturnValue)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetResponse()) ? 131071 : 524287);
    if (isSetResponse())
      hashCode = hashCode * 8191 + Response.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(ReturnValue);

    return hashCode;
  }

  @Override
  public int compareTo(ServerResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetResponse()).compareTo(other.isSetResponse());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResponse()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.Response, other.Response);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetReturnValue()).compareTo(other.isSetReturnValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReturnValue()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ReturnValue, other.ReturnValue);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ServerResponse(");
    boolean first = true;

    sb.append("Response:");
    if (this.Response == null) {
      sb.append("null");
    } else {
      sb.append(this.Response);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ReturnValue:");
    sb.append(this.ReturnValue);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ServerResponseStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ServerResponseStandardScheme getScheme() {
      return new ServerResponseStandardScheme();
    }
  }

  private static class ServerResponseStandardScheme extends org.apache.thrift.scheme.StandardScheme<ServerResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ServerResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESPONSE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.Response = iprot.readString();
              struct.setResponseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RETURN_VALUE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.ReturnValue = iprot.readI64();
              struct.setReturnValueIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ServerResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.Response != null) {
        oprot.writeFieldBegin(RESPONSE_FIELD_DESC);
        oprot.writeString(struct.Response);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(RETURN_VALUE_FIELD_DESC);
      oprot.writeI64(struct.ReturnValue);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ServerResponseTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ServerResponseTupleScheme getScheme() {
      return new ServerResponseTupleScheme();
    }
  }

  private static class ServerResponseTupleScheme extends org.apache.thrift.scheme.TupleScheme<ServerResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ServerResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetResponse()) {
        optionals.set(0);
      }
      if (struct.isSetReturnValue()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetResponse()) {
        oprot.writeString(struct.Response);
      }
      if (struct.isSetReturnValue()) {
        oprot.writeI64(struct.ReturnValue);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ServerResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.Response = iprot.readString();
        struct.setResponseIsSet(true);
      }
      if (incoming.get(1)) {
        struct.ReturnValue = iprot.readI64();
        struct.setReturnValueIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

