/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package WGit;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-04-02")
public enum Modes implements org.apache.thrift.TEnum {
  R(0),
  W(1),
  plus(2),
  C(3),
  D(4),
  WM(5),
  plusM(6),
  CM(7),
  DM(8),
  GitRecievePack(9),
  GitUploadPack(10),
  GitUploadArchive(11);

  private final int value;

  private Modes(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Modes findByValue(int value) { 
    switch (value) {
      case 0:
        return R;
      case 1:
        return W;
      case 2:
        return plus;
      case 3:
        return C;
      case 4:
        return D;
      case 5:
        return WM;
      case 6:
        return plusM;
      case 7:
        return CM;
      case 8:
        return DM;
      case 9:
        return GitRecievePack;
      case 10:
        return GitUploadPack;
      case 11:
        return GitUploadArchive;
      default:
        return null;
    }
  }
}
