/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package WGit;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-04-02")
public enum Trigger implements org.apache.thrift.TEnum {
  ACCESS_1(0),
  ACCESS_2(1),
  PRE_GIT(2),
  POST_GIT(3);

  private final int value;

  private Trigger(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Trigger findByValue(int value) { 
    switch (value) {
      case 0:
        return ACCESS_1;
      case 1:
        return ACCESS_2;
      case 2:
        return PRE_GIT;
      case 3:
        return POST_GIT;
      default:
        return null;
    }
  }
}
